name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install dbus
      run: sudo apt install libdbus-glib-1-dev
    - name: Build noti
      run: make
    # - name: Install noti
    #   run: sudo make install
    - name: Run noticat
      run: ./noticat -h
